### ISSUE TITLE
Adding new media library

### ISSUE THREAD

**Issue by matjazpotocnik** [BitPoet/MediaLibrary#1]
While adding new media library: I clicked "+ Add Library", entered title and hit Save. Since I didn't set MediaLibraryParent:

Notice: Trying to get property of non-object in C:\inetpub\wwwroot\wire\core\PagesEditor.php on line 258
ProcessWire: ProcessMediaLibraries: Can't save page 0: /e-en-library/: It has no parent assigned

I would also expect that after adding the library, redirection to the /admin/media should be made?

**Comment by BitPoet** [comment]
Thank you for the feedback! You're right, I need to add checks there (and maybe set a default of "home", got to think about that). And I forgot to comment in the redirect. A fixed version will be online soon.

**Comment by BitPoet** [comment]
I'm now defaulting to home as parent, so leaving it empty is no longer possible. The redirect should now also happen.

**Comment by matjazpotocnik** [comment]
Both is working now. Closing.
