### ISSUE TITLE
Info notice

### ISSUE THREAD

**Issue by matjazpotocnik** [BitPoet/MediaLibrary#2]
After new library is created, the message is displayed:

"Session: Creating media page šit named it under 1".
1. Instead of 1 (id) title should be used?
2. Notice page title "šit"? Page should be created with the name "sit", not "it" (replacing š with s, not removing it).

**Comment by BitPoet** [comment]
I've changed the message to only show the title, as it was unnecessarily verbose, but I've got to look into the character replacement issue more closely, as the module uses $sanitizer->pageName which should take care of transliteration. Which PW version are you using?

**Comment by BitPoet** [comment]
Okay, found the mistake. I've completely missed that $sanitizer->pageName needs to be given a second parameter to do character substitutions. Fix coming soon.

**Comment by matjazpotocnik** [comment]
Like $pagename = $this->sanitizer->pageName($pagetitle, Sanitizer::translate);

Ok, it's working now. Thank you. You should consider publishing to modules directory...
