### ISSUE TITLE
Removing folder/items

### ISSUE THREAD

**Issue by MarcelHekkert** [BitPoet/MediaLibrary#3]
Hey there,

I've just installed the module and noticed I cannot removea folder. Would be nice to have. Also, is there a reason for showing the media in the pages list? I think it would be better if this was optional.
Nonetheless a nice module. I hope to see if progress.

**Comment by BitPoet** [comment]
Thank you for the feedback. Removing libraries currently has to happen through the page tree, as they are basically just pages with the MediaLibrary template. Hiding them from the tree would add a lot of complexity. I'll take a look though if this is something doable. Some of the regular page functionality (like deletion, as you mentioned) would have to be added to the admin page beforehand, so this needs some thought.

**Comment by BitPoet** [comment]
Hiding the libraries from the page tree is now possible, and a delete button has been added to the Media page. There might be places where the libraries still show up (listers, etc.) though. The feature can be enabled in the module settings of MediaLibrary.
