### ISSUE TITLE
referencing using image picker

### ISSUE THREAD

**Issue by jmayermsi** [BitPoet/MediaLibrary#6]
If I wanted to be able to add an image picker field that is not located inside CKeditor how would I utilize this? I need to utilize a separate image field instead of using CKeditor for placement of my image. 

Thanks in advance

**Comment by BitPoet** [comment]
Sorry, I missed this issue.

That's actually a feature that goes beyond the scope of the module.

It might be possible with the free [FieldtypeImageReference](https://github.com/gebeer/FieldtypeImageReference), or the commercial [MediaManager](https://processwireshop.pw/plugins/media-manager/) might do that.
